name: Merge Repos Action

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Run merge_repos.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GIT_USER_NAME: "lsfreitas"
          GIT_USER_EMAIL: "luisfreitas440@gmail.com"
          TARGET_REPO_URL: "git@github.com:lsfreitas/target.git"
          SOURCE_REPO_URL: "git@github.com:lsfreitas/source.git"
        run: |
          python merge_repos.py
